#######################################################################
## This code was automatically generated by S4Coffee version X.X.XX  ##
## S4Coffee is available at XXX                                      ##
##                                                                   ##
## S4Coffee is copyright Gabriel Becker. The code in this file is    ##
## copyright the author(s) of the package in which it originally     ##
## appears.                                                          ##
#######################################################################

## Generated slot accessors for class ClassDirective

## Generated accessors for slot name

if (!exists("name") || !isGeneric("name")) setGeneric("name", function(x) standardGeneric("name"))

setMethod("name", "ClassDirective", function(x) x@name)

if (!exists("name<-") || !isGeneric("name<-")) setGeneric("name<-", function(x, value) standardGeneric("name<-"))

setMethod("name<-", "ClassDirective", function(x, value) {
    x@name = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "ClassDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "ClassDirective", function(x, value) {
    x@type = value
    x
})




## Generated slot accessors for class SlotDirective

## Generated accessors for slot name

if (!exists("name") || !isGeneric("name")) setGeneric("name", function(x) standardGeneric("name"))

setMethod("name", "SlotDirective", function(x) x@name)

if (!exists("name<-") || !isGeneric("name<-")) setGeneric("name<-", function(x, value) standardGeneric("name<-"))

setMethod("name<-", "SlotDirective", function(x, value) {
    x@name = value
    x
})





## Generated accessors for slot slotclass

if (!exists("slotclass") || !isGeneric("slotclass")) setGeneric("slotclass", function(x) standardGeneric("slotclass"))

setMethod("slotclass", "SlotDirective", function(x) x@slotclass)

if (!exists("slotclass<-") || !isGeneric("slotclass<-")) setGeneric("slotclass<-", function(x, value) standardGeneric("slotclass<-"))

setMethod("slotclass<-", "SlotDirective", function(x, value) {
    x@slotclass = value
    x
})








## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "SlotDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "SlotDirective", function(x, value) {
    x@type = value
    x
})




## Generated slot accessors for class SlotDefaultDirective

## Generated accessors for slot name

if (!exists("name") || !isGeneric("name")) setGeneric("name", function(x) standardGeneric("name"))

setMethod("name", "SlotDefaultDirective", function(x) x@name)

if (!exists("name<-") || !isGeneric("name<-")) setGeneric("name<-", function(x, value) standardGeneric("name<-"))

setMethod("name<-", "SlotDefaultDirective", function(x, value) {
    x@name = value
    x
})





## Generated accessors for slot value

if (!exists("value") || !isGeneric("value")) setGeneric("value", function(x) standardGeneric("value"))

setMethod("value", "SlotDefaultDirective", function(x) x@value)

if (!exists("value<-") || !isGeneric("value<-")) setGeneric("value<-", function(x, value) standardGeneric("value<-"))

setMethod("value<-", "SlotDefaultDirective", function(x, value) {
    x@value = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "SlotDefaultDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "SlotDefaultDirective", function(x, value) {
    x@type = value
    x
})




## Generated slot accessors for class AccessorsDirective

## Generated accessors for slot slotnames

if (!exists("slotnames") || !isGeneric("slotnames")) setGeneric("slotnames", function(x) standardGeneric("slotnames"))

setMethod("slotnames", "AccessorsDirective", function(x) x@slotnames)

if (!exists("slotnames<-") || !isGeneric("slotnames<-")) setGeneric("slotnames<-", function(x, value) standardGeneric("slotnames<-"))

setMethod("slotnames<-", "AccessorsDirective", function(x, value) {
    x@slotnames = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "AccessorsDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "AccessorsDirective", function(x, value) {
    x@type = value
    x
})




## Generated slot accessors for class MethodDirective

## Generated accessors for slot name

if (!exists("name") || !isGeneric("name")) setGeneric("name", function(x) standardGeneric("name"))

setMethod("name", "MethodDirective", function(x) x@name)

if (!exists("name<-") || !isGeneric("name<-")) setGeneric("name<-", function(x, value) standardGeneric("name<-"))

setMethod("name<-", "MethodDirective", function(x, value) {
    x@name = value
    x
})




## Generated slot accessors for class ContainsDirective

## Generated accessors for slot classnames

if (!exists("classnames") || !isGeneric("classnames")) setGeneric("classnames", function(x) standardGeneric("classnames"))

setMethod("classnames", "ContainsDirective", function(x) x@classnames)

if (!exists("classnames<-") || !isGeneric("classnames<-")) setGeneric("classnames<-", function(x, value) standardGeneric("classnames<-"))

setMethod("classnames<-", "ContainsDirective", function(x, value) {
    x@classnames = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "ContainsDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "ContainsDirective", function(x, value) {
    x@type = value
    x
})




## Generated slot accessors for class SigTypeDirective

## Generated accessors for slot argname

if (!exists("argname") || !isGeneric("argname")) setGeneric("argname", function(x) standardGeneric("argname"))

setMethod("argname", "SigTypeDirective", function(x) x@argname)

if (!exists("argname<-") || !isGeneric("argname<-")) setGeneric("argname<-", function(x, value) standardGeneric("argname<-"))

setMethod("argname<-", "SigTypeDirective", function(x, value) {
    x@argname = value
    x
})





## Generated accessors for slot argclass

if (!exists("argclass") || !isGeneric("argclass")) setGeneric("argclass", function(x) standardGeneric("argclass"))

setMethod("argclass", "SigTypeDirective", function(x) x@argclass)

if (!exists("argclass<-") || !isGeneric("argclass<-")) setGeneric("argclass<-", function(x, value) standardGeneric("argclass<-"))

setMethod("argclass<-", "SigTypeDirective", function(x, value) {
    x@argclass = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "SigTypeDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "SigTypeDirective", function(x, value) {
    x@type = value
    x
})




#########################################################################
## This code was automatically generated by S4Coffee version X.X.XX    ##
## S4Coffee is available for use under the XXX license at XXX          ##
##                                                                     ##
## S4Coffee was written by Gabriel Becker and is copyright Genentech,  ##
## Inc. Gabriel Becker and Genentech, Inc. waive all claims to         ##
## ownership or copyright of the generated code in this file with      ##
## the exception that this notice must be included, unaltered, in      ##
## any public distributions of this file or parts thereof. The code in ##
## this file is copyright the copyright holders of the template(s)     ##
## used to generate it.                                                ##
#########################################################################

## Generated slot accessors for class GenericDirective

## Generated accessors for slot name

if (!exists("name") || !isGeneric("name")) setGeneric("name", function(x) standardGeneric("name"))

setMethod("name", "GenericDirective", function(x) x@name)

if (!exists("name<-") || !isGeneric("name<-")) setGeneric("name<-", function(x, value) standardGeneric("name<-"))

setMethod("name<-", "GenericDirective", function(x, value) {
    x@name = value
    x
})





## Generated accessors for slot type

if (!exists("type") || !isGeneric("type")) setGeneric("type", function(x) standardGeneric("type"))

setMethod("type", "GenericDirective", function(x) x@type)

if (!exists("type<-") || !isGeneric("type<-")) setGeneric("type<-", function(x, value) standardGeneric("type<-"))

setMethod("type<-", "GenericDirective", function(x, value) {
    x@type = value
    x
})




