#######################################################################
## This code was automatically generated by S4Coffee version X.X.XX  ##
## S4Coffee is available at XXX                                      ##
##                                                                   ##
## S4Coffee is copyright Gabriel Becker. The code in this file is    ##
## copyright the author(s) of the package in which it originally     ##
## appears.                                                          ##
#######################################################################

## Generated slot accessors for class EntryPattern

## Generated accessors for slot single_words

setGeneric("single_words", function(x) standardGeneric("single_words"))

setMethod("single_words", "EntryPattern", function(x) x@single_words)

setGeneric("single_words<-", function(x, value) standardGeneric("single_words<-"))

setMethod("single_words<-", "EntryPattern", function(x, value) {
    x@single_words = value
    x
})





## Generated accessors for slot freeform_end

setGeneric("freeform_end", function(x) standardGeneric("freeform_end"))

setMethod("freeform_end", "EntryPattern", function(x) x@freeform_end)

setGeneric("freeform_end<-", function(x, value) standardGeneric("freeform_end<-"))

setMethod("freeform_end<-", "EntryPattern", function(x, value) {
    x@freeform_end = value
    x
})




