
.splashtext = c(
    "#########################################################################\n",
    sprintf("## This code was automatically generated by S4Coffee version %s     ##\n", packageVersion("S4Coffee")),
    "## S4Coffee is available for use under the Artistic-2.0 license at     ##\n",
    "## XXX                                                                 ##\n",
    "##                                                                     ##\n",
    "## S4Coffee was written by Gabriel Becker and is copyright Genentech,  ##\n",
    "## Inc. The code in this file is owned and copyright the S4Coffee      ##\n",
    "## user(s) who generated it.                                           ##\n",
    "##                                                                     ##\n",
    "## Do not edit this file by hand.                                      ##\n",
    "#########################################################################\n\n")

.prettify = function(x) as.character(parse(text = x, keep.source=FALSE))
